services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kapt-fastapi
    environment:
      MYSQL_HOST: Admin-KAPT
      MYSQL_PORT: 3307
      MYSQL_DATABASE: kapt_diecast
      MYSQL_USER: root
      MYSQL_PASSWORD: [KAPT_admin_123]
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  db:
    image: mysql:8.4
    container_name: kapt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: [KAPT_admin_123]
      MYSQL_DATABASE: kapt_diecast
      MYSQL_USER: root
      MYSQL_PASSWORD: [KAPT_admin_123]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
