apiVersion: v1
kind: ConfigMap
metadata:
  name: kapt-config
  namespace: default
data:
  APP_NAME: "Kapt Diecast Cloud"
  APP_VERSION: "1.0.0"
  BOOTSTRAP_ADMIN_EMAIL: "teekayyj@gmail.com"
  MYSQL_HOST: "kapt-db-dev.cpe0wimeipvx.ap-south-1.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "diecast_db"
  REDIS_HOST: "kapt-redis-dev.yr58g8.0001.aps1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  AWS_REGION: "ap-south-1"
  AWS_ENDPOINT_URL: "https://s3.ap-south-1.amazonaws.com"
  S3_BUCKET_NAME: "kapt-assets-dev"
  S3_BUCKET_DOMAIN_NAME: "kapt-assets-dev.s3.ap-south-1.amazonaws.com"
  GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/firebase-service-account.json"
