apiVersion: v1
kind: ConfigMap
metadata:
  name: kapt-config
  namespace: default
data:
  APP_NAME: "Kapt Diecast Cloud"
  APP_VERSION: "1.0.0"
  MYSQL_HOST: "diecast-db" # Sẽ cập nhật lúc Deploy bởi Terraform Output
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "diecast_db"
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "kapt-assets-dev"
  # S3 URL bị lược bỏ để thư viện tự chạy thẳng lên Cloud
  GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/firebase-service-account.json"
