apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapt-api
  namespace: default
  labels:
    app: kapt-api
spec:
  replicas: 3
  minReadySeconds: 5
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kapt-api
  template:
    metadata:
      labels:
        app: kapt-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: fastapi-app
          image: 128974585784.dkr.ecr.ap-south-1.amazonaws.com/kapt-api-backend:fix-checkout-1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kapt-config
            - secretRef:
                name: kapt-secret
          volumeMounts:
            - name: firebase-volume
              mountPath: /app/credentials
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-credentials
