apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapt-api
  namespace: default
  labels:
    app: kapt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kapt-api
  template:
    metadata:
      labels:
        app: kapt-api
    spec:
      containers:
        - name: fastapi-app
          image: 128974585784.dkr.ecr.ap-south-1.amazonaws.com/kapt-api-backend:45fb00c217afcd4a42c047f2c298ca5b20462c68
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: kapt-config
            - secretRef:
                name: kapt-secret
          volumeMounts:
            - name: firebase-volume
              mountPath: /app/credentials
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-credentials
