apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: default
type: Opaque
stringData:
  firebase-service-account.json: |
    {
      "placeholder": "Thực tế chuỗi JSON lấy từ Firebase Console sẽ được điền vào đây tại môi trường thật."
    }
