apiVersion: v1
kind: Secret
metadata:
  name: kapt-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "CHANGE_ME"
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
